# Generated by Django 5.1.1 on 2024-10-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CK', 'Cake'), ('IC', 'Ice-Cream'), ('CF', 'Coffee')], max_length=2)),
                ('product_image', models.ImageField(upload_to='things')),
            ],
        ),
    ]
