# Generated by Django 5.1.4 on 2025-02-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_carts_unique_together_carts_unique_cart_item'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carts',
            name='unique_cart_item',
        ),
    ]
