# Generated by Django 5.1.4 on 2025-02-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_carts_unique_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='district',
        ),
    ]
