# Generated by Django 5.1.4 on 2025-02-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
