# Generated by Django 5.1.4 on 2025-02-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_orderplaced_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='o_id',
            field=models.IntegerField(default=1, max_length=10, unique=True),
        ),
    ]
