# Generated by Django 5.1.4 on 2025-02-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_orderplaced_order_id_orderplaced_o_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='o_id',
        ),
    ]
